import patch_0 from './000_zoia_slightlyrandom.bin.json' with { type: 'json' }
import patch_1 from './001_zoia_SWARM.bin.json' with { type: 'json' }
import patch_2 from './002_zoia_Acid_wash.bin.json' with { type: 'json' }
import patch_3 from './003_zoia_FM_drums.bin.json' with { type: 'json' }
import patch_4 from './004_zoia_1Volt_Chord.bin.json' with { type: 'json' }
import patch_5 from './005_zoia_MultiVox.bin.json' with { type: 'json' }
import patch_6 from './006_zoia_Shim_Shim_Meree.bin.json' with { type: 'json' }
import patch_7 from './007_zoia_Space4rent.bin.json' with { type: 'json' }
import patch_8 from './008_zoia_Stretch_repeat.bin.json' with { type: 'json' }
import patch_9 from './009_zoia_Non_linear.bin.json' with { type: 'json' }
import patch_10 from './010_zoia_Upwards.bin.json' with { type: 'json' }
import patch_11 from './011_zoia_Grains_de_folie.bin.json' with { type: 'json' }
import patch_12 from './012_zoia_PhaDelRevDry.bin.json' with { type: 'json' }
import patch_13 from './013_zoia_Microsounds.bin.json' with { type: 'json' }
import patch_14 from './014_zoia_airport_loopsV2.bin.json' with { type: 'json' }
import patch_15 from './015_zoia_Phase_drag.bin.json' with { type: 'json' }
import patch_16 from './016_zoia_Tape_Return.bin.json' with { type: 'json' }
import patch_17 from './017_zoia_DegenerateGain3.bin.json' with { type: 'json' }
import patch_18 from './018_zoia_destroyyy.bin.json' with { type: 'json' }
import patch_19 from './019_zoia_Duck_Duck_Drive.bin.json' with { type: 'json' }
import patch_20 from './020_zoia_Resoverb.bin.json' with { type: 'json' }
import patch_21 from './021_zoia_Filter_twins.bin.json' with { type: 'json' }
import patch_22 from './022_zoia_DigiOp.bin.json' with { type: 'json' }
import patch_23 from './023_zoia_Quantize_n_Play.bin.json' with { type: 'json' }
import patch_24 from './024_zoia_skating_alone.bin.json' with { type: 'json' }
import patch_25 from './025_zoia_drumzz_not_dead.bin.json' with { type: 'json' }
import patch_26 from './026_zoia_DZO.bin.json' with { type: 'json' }
import patch_27 from './027_zoia_NARCC.bin.json' with { type: 'json' }
import patch_28 from './028_zoia_Modalate_this.bin.json' with { type: 'json' }
import patch_29 from './029_zoia_Risers.bin.json' with { type: 'json' }
import patch_30 from './030_zoia_1volt_3synths.bin.json' with { type: 'json' }
import patch_31 from './031_zoia_Feedbacker.bin.json' with { type: 'json' }
import patch_32 from './032_zoia_Green_Bank.bin.json' with { type: 'json' }
import patch_33 from './033_zoia_Convolving.bin.json' with { type: 'json' }
import patch_34 from './034_zoia_XYZebu.bin.json' with { type: 'json' }
import patch_35 from './035_zoia_Parts_V2_loop.bin.json' with { type: 'json' }
import patch_36 from './036_zoia_Meter_Made.bin.json' with { type: 'json' }
import patch_37 from './037_zoia_1978_Plate_V2.bin.json' with { type: 'json' }
import patch_38 from './038_zoia_Xover.bin.json' with { type: 'json' }
import patch_39 from './039_zoia_Fragments.bin.json' with { type: 'json' }
import patch_40 from './040_zoia_3011.bin.json' with { type: 'json' }
import patch_41 from './041_zoia_Spin_Cycle.bin.json' with { type: 'json' }
import patch_42 from './042_zoia_Synced_loopers.bin.json' with { type: 'json' }
import patch_43 from './043_zoia_LoopSampler.bin.json' with { type: 'json' }
import patch_44 from './044_zoia_Loop_seq.bin.json' with { type: 'json' }
import patch_45 from './045_zoia_Sliced_pie.bin.json' with { type: 'json' }
import patch_46 from './046_zoia_Playing_tag.bin.json' with { type: 'json' }
import patch_47 from './047_zoia_Arithmetic.bin.json' with { type: 'json' }
import patch_48 from './048_zoia_Quad_flex.bin.json' with { type: 'json' }
import patch_49 from './049_zoia_Not_My_Tempo.bin.json' with { type: 'json' }
import patch_50 from './050_zoia_Professor_Chaos.bin.json' with { type: 'json' }
import patch_51 from './051_zoia_PolyRhythmiZOIA.bin.json' with { type: 'json' }
import patch_52 from './052_zoia_Hide_and_Seq.bin.json' with { type: 'json' }
import patch_53 from './053_zoia_Turings_Dream.bin.json' with { type: 'json' }
import patch_54 from './054_zoia_Random_progress.bin.json' with { type: 'json' }
import patch_55 from './055_zoia_ProbableOutcome.bin.json' with { type: 'json' }
import patch_56 from './056_zoia_Boolean_foolin.bin.json' with { type: 'json' }
import patch_57 from './057_zoia_lfo_bank.bin.json' with { type: 'json' }
import patch_58 from './058_zoia_Noisy_Bug.bin.json' with { type: 'json' }
import patch_59 from './059_zoia_visualize_it.bin.json' with { type: 'json' }
export const patches: any[] = [patch_0,patch_1,patch_2,patch_3,patch_4,patch_5,patch_6,patch_7,patch_8,patch_9,patch_10,patch_11,patch_12,patch_13,patch_14,patch_15,patch_16,patch_17,patch_18,patch_19,patch_20,patch_21,patch_22,patch_23,patch_24,patch_25,patch_26,patch_27,patch_28,patch_29,patch_30,patch_31,patch_32,patch_33,patch_34,patch_35,patch_36,patch_37,patch_38,patch_39,patch_40,patch_41,patch_42,patch_43,patch_44,patch_45,patch_46,patch_47,patch_48,patch_49,patch_50,patch_51,patch_52,patch_53,patch_54,patch_55,patch_56,patch_57,patch_58,patch_59]