/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XSvg: typeof import('./src/components/XSvg.vue')['default']
    XSvgSymbol: typeof import('./src/components/XSvgSymbol.vue')['default']
  }
}
