export const DISPLAY_MODULE: string[][] = [
  ['SFilt'],
  ['AuI'],
  ['AuO'],
  ['Alia'],
  ['Seq'],
  [],
  ['ADS'],
  [],
  ['AMu', 'Aud Mu'],
  ['BC'],
  ['S&H', 'S&H'],
  ['O&D', 'O&D'],
  ['EnF', 'Env F'],
  ['DlyL'],
  ['Osci'],
  ['PBu'],
  ['Key'],
  ['CVI'],
  ['Step'],
  ['SL', 'Slew Lim'],
  ['MiNI', 'Mi Notes In'],
  ['MiCI'],
  ['Mlt'],
  ['Cmp'],
  ['MF'],
  ['PRv'],
  ['BDl', 'Buffer Dly'],
  ['APF', 'All Pass Filt'],
  ['Qnt'],
  ['Phs'],
  ['Loo'],
  ['ISw'],
  ['OSw'],
  ['AIS', 'Aud In Sw'],
  ['AOS', 'Aud Out Sw'],
  ['MiP', 'Mi Pressure'],
  ['OD', 'Onset Det'],
  ['Rhy'],
  ['Noi'],
  ['Rnd'],
  [],
  ['Tre'],
  ['TCtrl', 'Tone Ctrl'],
  ['DM', 'Dly w/ Mod'],
  ['Sto', 'Stom'],
  ['Val'],
  ['CDly'],
  ['CL'],
  ['CFilt'],
  ['CDi', 'Clock Div'],
  ['Com'],
  ['CR'],
  ['Trig'],
  ['SS', 'SS'],
  ['CPI', 'CP In'],
  ['CPO', 'CP Out'],
  ['UBu'],
  ['AP', 'Audio Pan'],
  ['PD', 'Pitch Det'],
  ['PS'],
  ['NO', 'Mi Note Out'],
  ['CO'],
  ['MPO'],
  ['BM', 'Bit Mod'],
  ['AB', 'Aud Balan'],
  ['Inv'],
  [],
  ['Gho'],
  ['Cab', 'Cab Sim'],
  ['Flg'],
  ['Chr'],
  ['Vib'],
  ['EFilt'],
  ['RM', 'Ring Mod'],
  ['HRv'],
  ['PPD', 'PPDly'],
  ['AMx'],
  ['CFF', 'CV Flip'],
  ['Dif'],
  ['RvL'],
  ['RRv', 'Room Rv'],
  ['Pix'],
  ['MiCI', 'Mi Clock In'],
  ['Grn'],
  ['ClO', 'ClkO'],
  ['TtC'],
  ['MPI', 'MiPBI'],
  ['CO4', 'CO4'],
  ['CI1'],
  ['CI2'],
  ['CI3'],
  ['CI4'],
  ['EHA', 'EHA', 'EHA'],
  ['EI1', 'EI1'],
  ['EI2', 'EI2'],
  ['EO1', 'EO1'],
  ['EO2', 'EO2', 'EO2'],
  ['PB1', 'PB1'],
  ['PB2', 'PB2'],
  ['CO1', 'CO1'],
  ['CO2', 'CO2'],
  ['CO3', 'CO3'],
  ['Smp'],
  ['DC', 'Device Ctrl'],
  ['CMx'],
  ['LG'],
  ['RDl', 'Rev Dly'],
  ['Uni'],
]
