export const DISPLAY_MODULE: string[][] = [
  ['SFilt'],
  ['AudI'],
  ['AO'],
  ['Alia'],
  ['Seq'],
  [],
  ['ADS'],
  [],
  ['AMu', 'Aud Mu'],
  ['BC'],
  ['S&H', 'S&H'],
  ['O&D', 'O&D'],
  ['EnF', 'Env F'],
  ['DlyL'],
  ['Osci'],
  ['PBu'],
  ['Key'],
  ['CVI'],
  ['Step'],
  ['SL'],
  ['MiNI', 'Mi Notes In'],
  ['MiCI'],
  ['Mlt'],
  ['Cmp'],
  ['MF'],
  ['PRv'],
  ['BDly', 'Buffer Dly'],
  ['APF', 'All Pass Filt'],
  ['Qnt'],
  ['Phs'],
  ['Loop'],
  ['ISw'],
  ['OSw'],
  ['AIS', 'Aud In Sw'],
  ['AOS', 'Aud Out Sw'],
  ['MiP', 'Mi Pressure'],
  ['OD', 'Onset Det'],
  ['Rhy'],
  ['Noi'],
  ['Rnd'],
  [],
  ['Tre'],
  ['TCtrl', 'Tone Ctrl'],
  ['D+M', 'Dly w/ Mod'],
  ['Sto', 'Stom'],
  ['Val'],
  ['CDly'],
  ['CL'],
  ['CFilt'],
  ['CDiv', 'Clock Div'],
  ['Com'],
  ['CR'],
  ['Trig'],
  ['SS', 'SS'],
  ['CECI', 'CECI'],
  ['CCO', 'CCO'],
  ['UBu'],
  ['AP', 'Aud Panner'],
  ['PD', 'Pitch Det'],
  ['PS'],
  ['MNO', 'Mi Note Out'],
  ['MCO'],
  ['MPO'],
  ['BM', 'Bit Mod'],
  ['AB', 'Aud Balance'],
  ['Inv'],
  [],
  ['Gho'],
  ['CS'],
  ['Flg'],
  ['Chr'],
  ['Vib'],
  ['EFilt'],
  ['RM', 'Ring Mod'],
  ['HRv'],
  ['PPD', 'PPDly'],
  ['AMx'],
  ['CFF', 'CV Flip'],
  ['Dif'],
  ['RvL'],
  ['RRv', 'Room Rv'],
  ['Pix'],
  ['MiCI', 'Mi Clock In'],
  ['Grn'],
  ['MCO', 'MiCO'],
  ['TtC'],
  ['MPBI', 'MiPBI'],
  ['ECO4', 'ECO4'],
  ['ECI1'],
  ['ECI2'],
  ['ECI3'],
  ['ECI4'],
  ['EHA', 'EHA', 'EHA'],
  ['EAI1', 'EAI1'],
  ['EAI2', 'EAI2'],
  ['EAO1', 'EAO1'],
  ['EAO2', 'EAO2', 'EAO2'],
  ['EP1', 'EP1'],
  ['EP2', 'EP2'],
  ['ECO1', 'ECO1'],
  ['ECO2', 'ECO2'],
  ['ECO3', 'ECO3'],
  ['Smp'],
  ['DC', 'Device Ctrl'],
  ['CMx'],
  ['LG'],
  ['RDly', 'Reverse Dly'],
  ['Uni'],
]
